import type { Config } from "tailwindcss";

export default {
  content: ["./app/**/{**,.client,.server}.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "var(--color-bg)",
        surface: "var(--color-surface)",
        border: "var(--color-border)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-tertiary": "var(--color-text-tertiary)",
        "deep-ocean": "var(--color-deep-ocean)",
        "ocean-blue": "var(--color-ocean-blue)",
        "reef-cyan": "var(--color-reef-cyan)",
        "mist-blue": "var(--color-mist-blue)",
        prelude: "var(--color-prelude)",
        "prelude-bg": "var(--color-prelude-bg)",
        bridge: "var(--color-bridge)",
        "bridge-bg": "var(--color-bridge-bg)",
        challenge: "var(--color-challenge)",
        "challenge-bg": "var(--color-challenge-bg)",
        epilogue: "var(--color-epilogue)",
        "epilogue-bg": "var(--color-epilogue-bg)",
        "admin-bg": "var(--color-admin-bg)",
        "admin-surface": "var(--color-admin-surface)",
        "admin-border": "var(--color-admin-border)",
        "admin-sidebar": "var(--color-admin-sidebar)",
        "admin-sidebar-text": "var(--color-admin-sidebar-text)",
        "admin-sidebar-active": "var(--color-admin-sidebar-active)",
        "admin-text": "var(--color-admin-text)",
        "admin-text-secondary": "var(--color-admin-text-secondary)",
        "admin-accent": "var(--color-admin-accent)",
        success: "var(--color-success)",
        warning: "var(--color-warning)",
        error: "var(--color-error)",
        info: "var(--color-info)",
      },
      spacing: {
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        8: "var(--space-8)",
        10: "var(--space-10)",
        12: "var(--space-12)",
        16: "var(--space-16)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        card: "var(--radius-lg)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
      },
      maxWidth: {
        reading: "var(--max-reading-width)",
        content: "var(--max-content-width)",
      },
      fontFamily: {
        sans: "var(--font-sans)",
      },
      fontSize: {
        sm: "var(--font-size-sm)",
        base: "var(--font-size-base)",
        lg: "var(--font-size-lg)",
        xl: "var(--font-size-xl)",
        "2xl": "var(--font-size-2xl)",
        "3xl": "var(--font-size-3xl)",
        "4xl": "var(--font-size-4xl)",
      },
      transitionDuration: {
        fast: "var(--duration-fast)",
        normal: "var(--duration-normal)",
        slow: "var(--duration-slow)",
      },
    },
  },
  plugins: [],
} satisfies Config;
