name = "divelog"
main = "build/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "divelog.ada-kr-pos.com", custom_domain = true }
]

[vars]
ADAKRPOS_API_KEY = "ak_277c6498-ee78-4f04-a09c-808d241f7d2c"
ADMIN_USER_ID = "usr_placeholder_replace_with_real_admin_id"
ADMIN_EMAILS = "sunkima26@pos.idserve.net"

[assets]
directory = "build/client"

[[d1_databases]]
binding = "DB"
database_name = "divelog-db"
database_id = "12a8007b-d92c-45cf-8bab-2d5692d704c1"

[[r2_buckets]]
binding = "R2"
bucket_name = "divelog-r2"

[[queues.producers]]
binding = "QUEUE"
queue = "divelog-queue"
