 import { type RouteConfig, layout, index, route } from "@react-router/dev/routes";

 
export default [
  layout("routes/_public.tsx", [
    index("routes/public/index.tsx"),
    route("journey", "routes/public/journey/index.tsx"),
    route("journey/:stageSlug", "routes/public/journey/$stageSlug.tsx"),
    route("logs", "routes/public/logs/index.tsx"),
    route("logs/:recordSlug", "routes/public/logs/$recordSlug.tsx"),
    route("logs/:recordSlug/edit", "routes/public/logs/$recordSlug.edit.tsx"),
    route("write", "routes/public/write/index.tsx"),
    route("write/note", "routes/public/write/note.tsx"),
    route("write/article", "routes/public/write/article.tsx"),
    route("logs/:recordSlug/details", "routes/public/logs/$recordSlug.details.tsx"),
    route("learners", "routes/public/learners/index.tsx"),
    route("learners/:learnerSlug", "routes/public/learners/$learnerSlug.tsx"),
    route("challenges", "routes/public/challenges/index.tsx"),
    route("challenges/:challengeSlug", "routes/public/challenges/$challengeSlug.tsx"),
    // [COLLAB_DISABLED] route("groups/:groupSlug", "routes/public/groups/$groupSlug.tsx"),
    route("memories/:stageSlug", "routes/public/memories/$stageSlug.tsx"),
    route("search", "routes/public/search.tsx"),
    route("tags", "routes/public/tags/index.tsx"),
    route("tags/:tagSlug", "routes/public/tags/$tagSlug.tsx"),
    route("inbox", "routes/public/inbox.tsx"),
    route("me", "routes/public/me.tsx"),
    route("settings", "routes/public/settings.tsx"),
    route("guide", "routes/public/guide.tsx"),
    route("style-reference", "routes/public/style-reference.tsx"),
  ]),
  layout("routes/_admin.tsx", [
    route("admin", "routes/admin/index.tsx"),
    route("admin/stages", "routes/admin/stages/index.tsx"),
    route("admin/stages/:stageId", "routes/admin/stages/$stageId.tsx"),
    route("admin/challenges", "routes/admin/challenges/index.tsx"),
    route("admin/challenges/:challengeId", "routes/admin/challenges/$challengeId.tsx"),
    route("admin/learners", "routes/admin/learners/index.tsx"),
    route("admin/learners/:learnerId", "routes/admin/learners/$learnerId.tsx"),
    route("admin/records", "routes/admin/records/index.tsx"),
    route("admin/records/:recordId", "routes/admin/records/$recordId.tsx"),
    route("admin/dialogue", "routes/admin/dialogue/index.tsx"),
    route("admin/dialogue/:responseId", "routes/admin/dialogue/$responseId.tsx"),
    // [COLLAB_DISABLED] route("admin/collaboration", "routes/admin/collaboration/index.tsx"),
    // [COLLAB_DISABLED] route("admin/collaboration/:groupId", "routes/admin/collaboration/$groupId.tsx"),
    route("admin/curation", "routes/admin/curation.tsx"),
    route("admin/memories", "routes/admin/memories/index.tsx"),
    route("admin/memories/:stageId", "routes/admin/memories/$stageId.tsx"),
    route("admin/templates", "routes/admin/templates/index.tsx"),
    route("admin/templates/:templateId", "routes/admin/templates/$templateId.tsx"),
    route("admin/tags", "routes/admin/tags.tsx"),
    route("admin/analytics", "routes/admin/analytics.tsx"),
    route("admin/settings", "routes/admin/settings.tsx"),
    route("admin/roles", "routes/admin/roles.tsx"),
    route("admin/audit", "routes/admin/audit.tsx"),
  ]),
  route("api/upload", "routes/api/upload.tsx"),
  route("api/images/*", "routes/api/images.$.tsx"),
  route("api/notifications", "routes/api/notifications.tsx"),
  route("api/autosave", "routes/api/autosave.tsx"),
  route("api/search-records", "routes/api/search-records.tsx"),
  route("api/search-learners", "routes/api/search-learners.tsx"),
] satisfies RouteConfig;
