import { type RouteConfig, layout, index, route } from "@react-router/dev/routes";

export default [
  layout("routes/_public.tsx", [
    index("routes/_public._index.tsx"),
    route("journey", "routes/_public.journey.tsx"),
    route("journey/:stageSlug", "routes/_public.journey.$stageSlug.tsx"),
    route("logs", "routes/_public.logs._index.tsx"),
    route("logs/:recordSlug", "routes/_public.logs.$recordSlug.tsx"),
    route("logs/:recordSlug/edit", "routes/_public.logs.$recordSlug.edit.tsx"),
    route("write", "routes/_public.write.tsx"),
    route("write/note", "routes/_public.write.note.tsx"),
    route("write/article", "routes/_public.write.article.tsx"),
    route("logs/:recordSlug/details", "routes/_public.logs.$recordSlug.details.tsx"),
    route("learners", "routes/_public.learners._index.tsx"),
    route("learners/:learnerSlug", "routes/_public.learners.$learnerSlug.tsx"),
    route("challenges", "routes/_public.challenges._index.tsx"),
    route("challenges/:challengeSlug", "routes/_public.challenges.$challengeSlug.tsx"),
    route("groups/:groupSlug", "routes/_public.groups.$groupSlug.tsx"),
    route("memories/:stageSlug", "routes/_public.memories.$stageSlug.tsx"),
    route("search", "routes/_public.search.tsx"),
    route("tags", "routes/_public.tags.tsx"),
    route("tags/:tagSlug", "routes/_public.tags.$tagSlug.tsx"),
    route("inbox", "routes/_public.inbox.tsx"),
    route("me", "routes/_public.me.tsx"),
    route("settings", "routes/_public.settings.tsx"),
    route("guide", "routes/_public.guide.tsx"),
  ]),
  layout("routes/_admin.tsx", [
    route("admin", "routes/_admin.admin._index.tsx"),
    route("admin/stages", "routes/_admin.admin.stages._index.tsx"),
    route("admin/stages/:stageId", "routes/_admin.admin.stages.$stageId.tsx"),
    route("admin/challenges", "routes/_admin.admin.challenges._index.tsx"),
    route("admin/challenges/:challengeId", "routes/_admin.admin.challenges.$challengeId.tsx"),
    route("admin/learners", "routes/_admin.admin.learners._index.tsx"),
    route("admin/learners/:learnerId", "routes/_admin.admin.learners.$learnerId.tsx"),
    route("admin/records", "routes/_admin.admin.records._index.tsx"),
    route("admin/records/:recordId", "routes/_admin.admin.records.$recordId.tsx"),
    route("admin/dialogue", "routes/_admin.admin.dialogue._index.tsx"),
    route("admin/dialogue/:responseId", "routes/_admin.admin.dialogue.$responseId.tsx"),
    route("admin/collaboration", "routes/_admin.admin.collaboration._index.tsx"),
    route("admin/collaboration/:groupId", "routes/_admin.admin.collaboration.$groupId.tsx"),
    route("admin/curation", "routes/_admin.admin.curation.tsx"),
    route("admin/memories", "routes/_admin.admin.memories._index.tsx"),
    route("admin/memories/:stageId", "routes/_admin.admin.memories.$stageId.tsx"),
    route("admin/templates", "routes/_admin.admin.templates._index.tsx"),
    route("admin/templates/:templateId", "routes/_admin.admin.templates.$templateId.tsx"),
    route("admin/tags", "routes/_admin.admin.tags.tsx"),
    route("admin/analytics", "routes/_admin.admin.analytics.tsx"),
    route("admin/settings", "routes/_admin.admin.settings.tsx"),
    route("admin/roles", "routes/_admin.admin.roles.tsx"),
    route("admin/audit", "routes/_admin.admin.audit.tsx"),
  ]),
  route("api/upload", "routes/api.upload.tsx"),
  route("api/images/*", "routes/api.images.$.tsx"),
] satisfies RouteConfig;
